# fly.toml app configuration file generated for twilight-butterfly-9726 on 2023-05-09T17:35:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twilight-butterfly-9726"
primary_region = "atl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
