#!/usr/bin/env ruby

require 'json'
require 'openai'

if ENV['OPENAI_TOKEN'].nil?
  $stderr.puts "OPENAI_TOKEN not set"
  exit 1
end

text = STDIN.read.gsub( /\s\s/, "")

client = OpenAI::Client.new(access_token: ENV['OPENAI_TOKEN'])

content = "#{text}\n\ntl;dr\n"
response = client.chat(
  parameters: {
      model: "gpt-3.5-turbo", # Required.
      messages: [{ role: "user", content: content}], # Required.
      temperature: 0.7,
  })

if response['error']
  require 'pp'
  pp response
  puts response['error']['message']
end
puts "\n"
puts response.dig("choices", 0, "message", "content")