#!/usr/bin/env ruby

require 'net/http'
require 'nokogiri'
require 'json'
require 'openai'

if ARGV[0].nil?
  $stderr.puts "summarize <url>"
  exit 1
end

if ENV['OPENAI_TOKEN'].nil?
  $stderr.puts "OPENAI_TOKEN not set"
  exit 1
end

url = ARGV[0]
unless url =~  URI::DEFAULT_PARSER.regexp[:ABS_URI]
  $stderr.puts "#{url} is not a valid URL"
  exit 1
end

uri = URI(ARGV[0])
response = Net::HTTP.get_response(uri)

doc = Nokogiri::HTML(response.body)

doc.xpath('//script').remove # remove script tags
doc.xpath('//style').remove  # remove style tags
text = doc.xpath('//text()').text.strip.gsub(/\s\s/, "")

client = OpenAI::Client.new(access_token: ENV['OPENAI_TOKEN'])

content = "#{text}\n\ntl;dr\n"
response = client.chat(
  parameters: {
      model: "gpt-3.5-turbo", # Required.
      messages: [{ role: "user", content: content}], # Required.
      temperature: 0.7,
  })

puts "\n"
puts response.dig("choices", 0, "message", "content")